spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.200.135/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true


server:
  context-path: /sell

logging:
  pattern:
    console: "%d - %msg%n"


wechat:
  mpAppId: wx645b35f65d3c98cf
  mpAppSecret: 1a133181d9f641cf8564f69d036824e3
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://detrxi.natappfree.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://detrxi.natappfree.cc
  wechatOpenAuthorize: http://eeipeh.natappfree.cc
  sell: http://eeipeh.natappfree.cc

